targets:
  $default:
    builders:
      route_generator|route_builder:
        enabled: true
        options:
          input_files: 'lib/src/pages/*.dart'
          output_file: 'lib/routes/routes.dart'
          sort_assets: false