name: app_localization
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mustache_template: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - resources/lang/en.json
     - resources/lang/he.json
     - resources/lang/fr.json
     - resources/lang/hi.json
  #   - images/a_dot_ham.jpeg