// GENERATED CODE. DO NOT MODIFY. Generated by RoutesGenerator.

import 'package:flutter/material.dart';
import 'package:app_localization/src/pages/login_page.dart';

class AppRoutes {

  //login page route
  static void navigateToLoginPage(BuildContext context, String? data, int val) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => LoginPage(data: data, val: val)),
    );
  }
}
